name: fastmarket
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    go_router: ^15.1.2
    flutter_svg: ^2.1.0
    lottie: ^3.3.1

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0
    build_runner: ^2.4.15
    flutter_gen_runner: ^5.10.0

flutter_gen:
    output: lib/gen/ # Optional (default: lib/gen/)
    line_length: 80 # Optional (default: 80)

    # Optional
    integrations:
        image: true
        flutter_svg: true
        rive: true
        lottie: true

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/image/
        - assets/icon/
        - assets/lottie/
        - assets/svg/
        - assets/env/
