name: fastmarket
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ^3.7.2

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.8
    go_router: ^15.1.2
    flutter_svg: ^2.1.0
    lottie: ^3.3.1
    flutter_bloc: ^9.1.1
    retrofit: ^4.4.2
    dio: ^5.8.0+1
    freezed_annotation: ^3.0.0
    json_annotation: ^4.9.0
    get_it: ^8.0.3
    logger: ^2.5.0
    mocktail: ^1.0.4
    cached_network_image: ^3.4.1
    bloc_concurrency: ^0.3.0
    injectable: ^2.5.0
    intl: ^0.20.2

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^5.0.0
    build_runner: ^2.4.15
    flutter_gen_runner: ^5.10.0
    freezed: ^3.0.6
    json_serializable: ^6.9.5
    retrofit_generator: ^9.2.0
    injectable_generator: ^2.7.0

flutter_gen:
    output: lib/gen/ # Optional (default: lib/gen/)
    line_length: 80 # Optional (default: 80)

    # Optional
    integrations:
        image: true
        flutter_svg: true
        rive: true
        lottie: true

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/image/
        - assets/icon/
        - assets/lottie/
        - assets/svg/
        - assets/env/
