// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fastmarket/data/entity/display/cart/cart.entity.dart';
import 'package:fastmarket/data/entity/display/product_info/product_info.entity.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartEntityAdapter());
    registerAdapter(ProductInfoEntityAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartEntityAdapter());
    registerAdapter(ProductInfoEntityAdapter());
  }
}
